package com.health_insurance.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class X implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public X() {
    }




}